[package]
name = "ask-gpt"
version = "0.1.0"
edition = "2024"
authors = ["Zhehan Wang <zhehan0110@gmail.com>"]
description = "A CLI tool to interact with Useful GPT APIs. Now only support DeepSeek."
repository = "github.com/wswzhws/ask-gpt"
license = "MIT"

[dependencies]

